import "./globals.css";
import localFont from 'next/font/local';
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CustomCursor from "@/components/CustomCursor";

const spaceMono = localFont({
  src: '../../public/fonts/GeneralSans-Bold.otf',
  variable: '--font-space-mono',
  display: 'swap',
});

const neue = localFont({
  src: '../../public/fonts/PPNeueMontreal-Medium.otf',
  variable: '--font-neue-montreal',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`  scroller-hidden ${spaceMono.variable} ${neue.variable}`}>
      <body className= {`${spaceMono.className} ${neue.className} antialiased`}>      
          <CustomCursor />
          <Navbar />
          {children}
          <Footer />
      </body>

    </html>
  );
}
